name: Parallel Jobs

on: push

jobs: 
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo hello world
        sleep 20
  windows:
    runs-on: windows-latest
    steps:
    - run: echo hello world
  macos:
    runs-on: macos-latest
    steps:
    - run: |
        echo hello world
        sleep 20
